name: publish master to pypi

on:
  push:
    branches:
      - master
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Build
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine
        python -m build
    - name: Publish on pypi
      run: |
        twine upload dist/*
      env:
        TWINE_PASSWORD: ${{ secrets.PYPITOKEN }}
        TWINE_USERNAME: __token__
